//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int musteriID { get; set; }
        public string misim { get; set; }
        public string msoyisim { get; set; }
        public string mTC { get; set; }
        public string mmail { get; set; }
        public string mTel { get; set; }
        public string mcinsiyet { get; set; }
    }
}
