//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personeller
    {
        public int personelID { get; set; }
        public string perisim { get; set; }
        public string persoyad { get; set; }
        public string perTC { get; set; }
        public string perTel { get; set; }
        public string permail { get; set; }
        public string pernick { get; set; }
        public string persifre { get; set; }
        public string pgorev { get; set; }
        public string padres { get; set; }
        public string pcinsiyet { get; set; }
    }
}
