//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        public int siparisID { get; set; }
        public Nullable<int> urunID { get; set; }
        public Nullable<int> masaID { get; set; }
        public Nullable<double> urunfiyati { get; set; }
        public Nullable<bool> masadurum { get; set; }
        public string masano { get; set; }
    
        public virtual Urunler Urunler { get; set; }
    }
}
